### ISSUE TITLE
Strange behavior when using component with default values

### ISSUE THREAD

**Issue by puranjayjain** [jifalops/app-toast#3]
First of all a very superb component >>> paper toast.

Some of the things I would like to point out and fix if a PR is approved.
1. Why do you need the reset properties? it is redundant as properties are already set with their value.
2. From 1. this creates complications like setting properties via show method which is not how they should be set, instead they should be passed via individual property bindings or set on the element on declaration.
e.g
 Setting on the element
```
<app-toast show-cancel></app-toast>
```

**Comment by jifalops** [comment]
The properties can be declared statically in markup, using property bindings, or using the `show` method. The underlying paper-toast sets properties using the show method, so it makes sense to use a similar API.

The reason for the reset function is that properties persist after the toast has been shown. This is a problem when showing the toast from multiple locations. For example if using the toast with `app-drawer-layout`, it must be placed outside of app-drawer-layout to be displayed properly -- an issue with various overlay elements.

I agree that the reset function should be removed since it's functionality is not clear without looking at the code and what it actually does is pretty hackish. The ideal solution is to use the official `iron-swipeable-container`, which removes swiped elements from the DOM, and then re-add the element after it is swiped. Doing this proved to be very difficult so far.

**Comment by jifalops** [comment]
What strange behavior are you talking about?

**Comment by puranjayjain** [comment]
See my PR I have tried solving some of the underlying problems, also keeping the api intact. The strange behavior is that since you have mentioned some properties as default, even if they are not passed they should work. Also open method was missing which enabled me to do exactly that. Please comment on the PR if there are any problems or not so that we can make this component better.

**Comment by jifalops** [comment]
In the next release I'll deprecate the `reset` function and add the `open` alias for `show`. Note you can call show() without arguments. 

> The strange behavior is that since you have mentioned some properties as default, even if they are not passed they should work.

That is how it works so I'm not seeing an issue. Only properties that are passed are changed. If no properties are passed it is shown with its current properties.

**Comment by puranjayjain** [comment]
That'll be great. But properties like showChanged with its default value have no effect whatsoever, can you please look into that also?
